pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
               // sh 'mvn -B -DskipTests clean package'
                def mvnHome = tool  name: 'maven-3'  , type: 'maven' 
                sh"${mvnHome}/bin/mvn package"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage(' git Checkout') {
             steps {
               git credentialsId: 'cloudR123', url: 'http://github.com/Mrihab/simple-java-maven-app'
        }
    }
       
    //    stage("build & SonarQube analysis") {
          //  agent any
           // steps {
            //  withSonarQubeEnv('My SonarQube Server') {
                  
                //sh 'mvn sonar:sonar \
  //-Dsonar.projectKey=Test \
  //-Dsonar.host.url=http://192.168.159.132:9000 \
 // -Dsonar.login=be1767e5277e08e91f5eb1fa5a93f19a00e9346f'
//}
     //       }
        //  }
        //  stage("Quality Gate") {
          //  steps {
            //  timeout(time: 1, unit: 'HOURS') {
              //  waitForQualityGate abortPipeline: false
             // }
            //}
         // }
        
        
    }
}
